[package]
name = "rust-duk"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
needletail = "0.6.3"
hyperfine = "1.19.0"
rustc-hash = "2.1.1"
samply = "0.13.1"
rayon = "1.10.0"
bincode = "2.0.1"

[profile.release]
debug = 1
