[package]
name = "rust-duk"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "2.0.1"
bio = "2.3.0"
clap = { version = "4.5.41", features = ["derive"] }
indicatif = "0.18.0"
needletail = "0.6.3"
rayon = "1.10.0"
ahash = "0.8.12"
hyperfine = "1.19.0"
